CREATE TABLE anime ( 
	id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	title_eng VARCHAR(255) NOT NULL,
	title_native VARCHAR(255),
	title_alt VARCHAR(1023),
	votes_mal INT UNSIGNED,
	score_mal DECIMAL(4, 2),
	id_mal INT UNSIGNED,
	premiered VARCHAR(31),
	type VARCHAR(15),
	episodes INT UNSIGNED,
	duration VARCHAR(31),
	source VARCHAR(31),
	link_mal VARCHAR(255),
	link_ap VARCHAR(255),
	img VARCHAR(255)
) CHARACTER SET utf8 COLLATE utf8_unicode_ci;

CREATE TABLE anime_tag (
	id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	name VARCHAR(255) NOT NULL
) CHARACTER SET utf8 COLLATE utf8_unicode_ci;

CREATE TABLE anime_tag_mapping (
	anime_id BIGINT UNSIGNED NOT NULL,
	tag_id BIGINT UNSIGNED NOT NULL,
	FOREIGN KEY (anime_id) REFERENCES anime (id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (tag_id) REFERENCES anime_tag (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE waifu (
	id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	name_eng VARCHAR(255) NOT NULL,
	name_native VARCHAR(255),
	name_alt VARCHAR(255),
	gender VARCHAR(15),
	role VARCHAR(31),
	hair_color VARCHAR(31),
	likes_ap INT,
	dislikes_ap INT,
	link_ap VARCHAR(255),
	link_mal VARCHAR(255),
	img VARCHAR(255)
) CHARACTER SET utf8 COLLATE utf8_unicode_ci;

CREATE TABLE waifu_tag (
	id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	name VARCHAR(255) NOT NULL
) CHARACTER SET utf8 COLLATE utf8_unicode_ci;

CREATE TABLE waifu_tag_mapping (
	waifu_id BIGINT UNSIGNED NOT NULL,
	tag_id BIGINT UNSIGNED NOT NULL,
	votes INT UNSIGNED DEFAULT 0 NOT NULL,
	FOREIGN KEY (waifu_id) REFERENCES waifu (id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (tag_id) REFERENCES waifu_tag (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE anime_to_waifu_mapping (
	anime_id BIGINT UNSIGNED NOT NULL,
	waifu_id BIGINT UNSIGNED NOT NULL,
	FOREIGN KEY (anime_id) REFERENCES anime (id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (waifu_id) REFERENCES waifu (id) ON DELETE CASCADE ON UPDATE CASCADE
);
